#!/usr/bin/env bash
# =============================================================================
# build-scalapack-perlmutter.sh
#
# Build netlib scaLAPACK 2.2.0 on NERSC Perlmutter against the same toolchain
# used for VASP GPU (nvfortran/nvc + cray-mpich/8.1.30 + cray-libsci NVIDIA
# variant for BLAS/LAPACK).
#
# Why we need this: cray-libsci/25.09 ships libsci_nvidia (BLAS+LAPACK) but
# does NOT ship a scaLAPACK companion under the NVIDIA subtree, and the
# scaLAPACK bundled in NVHPC's HPC-X/OpenMPI is built against OpenMPI (not
# cray-mpich) so it is ABI-incompatible with everything else here. Building
# from netlib gives us a scaLAPACK linked against cray-mpich/8.1.30, which is
# what VASP (and the rest of the matsim toolchain) speaks.
#
# Usage:
#   bash scripts/setup/perlmutter/build-scalapack-perlmutter.sh
#
# Optional overrides:
#   SCALAPACK_VERSION=2.2.0
#   SCALAPACK_ROOT=<repo>/external/scalapack
#   PREFIX=<SCALAPACK_ROOT>/install      # final install dir
#   NCORES=auto
#   CLEAN_BUILD=0|1
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"
REPO="$(cd "${SCRIPT_DIR}/../../.." 2>/dev/null && pwd)"
[[ -f "${REPO}/pyproject.toml" ]] || { echo "ERROR: cannot detect repo root" >&2; exit 1; }

SCALAPACK_VERSION="${SCALAPACK_VERSION:-2.2.0}"
SCALAPACK_ROOT="${SCALAPACK_ROOT:-${REPO}/external/scalapack}"
PREFIX="${PREFIX:-${SCALAPACK_ROOT}/install}"
CLEAN_BUILD="${CLEAN_BUILD:-0}"
NCORES="${NCORES:-$(nproc 2>/dev/null || echo 8)}"

SRC="${SCALAPACK_ROOT}/scalapack-${SCALAPACK_VERSION}"
TARBALL="${SCALAPACK_ROOT}/scalapack-${SCALAPACK_VERSION}.tgz"
URL="https://netlib.org/scalapack/scalapack-${SCALAPACK_VERSION}.tgz"
BUILD="${SCALAPACK_ROOT}/build-${SCALAPACK_VERSION}"

log()  { printf '\033[1;34m[scalapack-pm]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[scalapack-pm]\033[0m %s\n' "$*" >&2; exit 1; }

# --- module stack (same as VASP build) ---------------------------------------
init_modules() {
    if command -v module >/dev/null 2>&1; then return 0; fi
    [[ -f /etc/profile.d/modules.sh   ]] && source /etc/profile.d/modules.sh
    [[ -f /usr/share/lmod/lmod/init/bash ]] && source /usr/share/lmod/lmod/init/bash
    command -v module >/dev/null 2>&1 || die "module command not found"
}
init_modules
# shellcheck disable=SC1091
source "${REPO}/scripts/setup/perlmutter/perlmutter-module-stack.sh"
load_perlmutter_modules_nvidia
ml cmake 2>/dev/null || true

if ! command -v nvfortran >/dev/null 2>&1; then
    export PATH="/opt/nvidia/hpc_sdk/Linux_x86_64/25.5/compilers/bin:${PATH}"
fi
command -v nvfortran >/dev/null 2>&1 || die "nvfortran not on PATH"
command -v nvc       >/dev/null 2>&1 || die "nvc not on PATH"

MPICH_DIR="${MPICH_DIR:?cray-mpich not loaded}"
LIBSCI_PREFIX="${CRAY_LIBSCI_PREFIX:?cray-libsci not loaded}"
# Resolve the NVIDIA variant of cray-libsci (BLAS/LAPACK linked into scaLAPACK).
LIBSCI_ROOT="${LIBSCI_PREFIX%/GNU/*}"; LIBSCI_ROOT="${LIBSCI_ROOT%/CRAY/*}"
LIBSCI_ROOT="${LIBSCI_ROOT%/INTEL/*}"; LIBSCI_ROOT="${LIBSCI_ROOT%/AOCC/*}"
LIBSCI_NVIDIA="$(ls -d ${LIBSCI_ROOT}/NVIDIA/*/x86_64 2>/dev/null | sort -V | tail -1)"
[[ -d "${LIBSCI_NVIDIA}" ]] || die "NVIDIA variant of cray-libsci not found"

# cray-mpich GTL (CUDA-aware transport) for nvidia80
MPICH_ROOT="${CRAY_MPICH_ROOTDIR:-${MPICH_DIR%/ofi/*}}"
GTL_DIR="${MPICH_ROOT}/gtl/lib"

log "=========================================="
log "scaLAPACK ${SCALAPACK_VERSION} build on Perlmutter"
log "Date:          $(date)"
log "Source:        ${SRC}"
log "Build:         ${BUILD}"
log "Install:       ${PREFIX}"
log "MPICH_DIR:     ${MPICH_DIR}"
log "LIBSCI_NVIDIA: ${LIBSCI_NVIDIA}"
log "GTL_DIR:       ${GTL_DIR}"
log "Cores:         ${NCORES}"
log "=========================================="

# --- fetch + extract ---------------------------------------------------------
mkdir -p "${SCALAPACK_ROOT}"
if [[ ! -f "${TARBALL}" ]]; then
    log "Downloading ${URL}"
    curl -fsSL --max-time 120 -o "${TARBALL}" "${URL}"
fi
if [[ ! -d "${SRC}" ]]; then
    log "Extracting ${TARBALL}"
    tar xzf "${TARBALL}" -C "${SCALAPACK_ROOT}"
fi
[[ -d "${SRC}" ]] || die "scaLAPACK source not found at ${SRC}"

# --- configure + build via classic netlib SLmake.inc + make lib --------------
# We bypass the upstream CMake build because its FindMPI cannot cope with
# nvc/nvfortran (no -show flag) when fed manual MPI hints.
if [[ "${CLEAN_BUILD}" == "1" ]]; then
    log "Cleaning previous build"
    ( cd "${SRC}" && make -s clean 2>/dev/null || true )
    rm -rf "${PREFIX}"
fi
mkdir -p "${PREFIX}/lib" "${PREFIX}/include"

SLMAKE="${SRC}/SLmake.inc"
log "Writing ${SLMAKE}"
cat > "${SLMAKE}" <<EOF
# Auto-generated by build-scalapack-perlmutter.sh
# nvfortran/nvc + cray-mpich/8.1.30 + cray-libsci NVIDIA (BLAS/LAPACK)

SHELL          = /bin/sh
FC             = nvfortran
CC             = nvc
# CDEFS controls the Fortran name-mangling macro used in REDIST/BLACS C
# sources. Without -DAdd_ the wrappers like pzgemr2d_/pcgemr2d_/pztrmr2d_
# are not emitted, and any client linking against libscalapack.a fails
# with "undefined reference to pzgemr2d_" at the final link.
CDEFS          = -DAdd_
NOOPT          = -O0 -fPIC
FCFLAGS        = -O2 -fPIC -mp -I${MPICH_DIR}/include
CCFLAGS        = -O2 -fPIC -mp -I${MPICH_DIR}/include

# scaLAPACK builds an archive only; we set ARCH/AR/RANLIB explicitly.
ARCH           = ar
ARCHFLAGS      = cr
RANLIB         = ranlib
SCALAPACKLIB   = libscalapack.a

# BLAS/LAPACK from cray-libsci (NVIDIA variant).
BLASLIB        = -L${LIBSCI_NVIDIA}/lib -lsci_nvidia_mp
LAPACKLIB      = \$(BLASLIB)

# Linker library list (used only by the test executables, which we skip).
LIBS           = \$(LAPACKLIB) \$(BLASLIB)
EOF

log "Building libscalapack.a (target: lib, serial -- upstream Makefile races on parallel 'ar cr')"
( cd "${SRC}" && make -j 1 lib ) 2>&1 | tee "${SCALAPACK_ROOT}/make.log" | tail -200

# Install: copy the archive to ${PREFIX}/lib.
LIB_SRC="${SRC}/libscalapack.a"
[[ -f "${LIB_SRC}" ]] || die "libscalapack.a not produced; check ${SCALAPACK_ROOT}/make.log"
cp -f "${LIB_SRC}" "${PREFIX}/lib/libscalapack.a"

# Sanity check
LIB="${PREFIX}/lib/libscalapack.a"
[[ -f "${LIB}" ]] || LIB="${PREFIX}/lib64/libscalapack.a"
[[ -f "${LIB}" ]] || die "libscalapack.a not produced under ${PREFIX}"

log "Built: ${LIB}"
log "Symbols (sample):"
nm "${LIB}" 2>/dev/null | grep -E ' T (pdgemm_|pdpotrf_|blacs_pinfo_)' | head
log "Done."
